server:
  port: 8761

spring:
  application:
    name: ecommerce-discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # ???? true -> ??? ??? ???? ???? ??? ???? false? ??
    # ??? ?? ??? ????, ?? ??? ??? ??? ?? ?? ???????? ??? ????? ??? ???? ??? ? ??? ?? ??? ???? ??? ?? ?